### ISSUE TITLE
How to use with React?

### ISSUE THREAD

**Issue by blokhin** [basf/svelte-spectre#10]
e.g. https://www.npmjs.com/package/svelte-adapter

**Comment by SiggiSmara** [comment]
Also think about vue/nuxt which is used a quite a lot inside of BASF?

**Comment by Valexr** [comment]
> Also think about vue/nuxt which is used a quite a lot inside of BASF? I would say in terms of the big frameworks Angular and Vue/nuxt are used more than React inside of BASF.

In progress🤓
And what do think about [Svelte](https://svelte.dev) like frontend-framework & [SvelteKit](https://kit.svelte.dev) like app-framework for yours apps?

**Comment by blokhin** [comment]
At some point in time, we have decided not to support the other frameworks than Svelte (such as React) since there are plenty of the UI-kits existing in their ecosystems, also based on Spectre.css. Furthermore, the features offered here by `svelte-spectre` are not really unique, they exist in the other UI-kits or at least can be easily implemented there. On the other hand, `svelte-spectre` presents the first integration of Svelte with Spectre.css (and presumably the richest and most convenient one!).
