### ISSUE TITLE
Svelte Reactivity doesn't work (PeriodicTable)

### ISSUE THREAD

**Issue by pyoner** [basf/svelte-spectre#124]
https://github.com/basf/svelte-spectre/blob/a99c8555fadede467486b34591837e9e76ac7e4d/src/lib/components/PeriodicTable/PeriodicTable.svelte#L161

use  ES6 spread syntax:
```js
selected = [...selected];
```

**Comment by blokhin** [comment]
OK, I see here https://svelte.dev/tutorial/updating-arrays-and-objects:

> ...won't trigger reactivity on obj.foo.bar, unless you follow it up with obj = obj.
