### ISSUE TITLE
Demo website page reload is broken due to trailing slash not supported on GH

### ISSUE THREAD

**Issue by blokhin** [basf/svelte-spectre#128]
e.g. https://kit.metis.science/docs/components/periodictable/

**Comment by GlistenSTAR** [comment]
Hello, @blokhin 
How are you?
Did you fix the trailing slash problem in svelte-specter?

**Comment by blokhin** [comment]
Temporary solution with https://github.com/tilde-lab/svelte-spectre-storybook/commit/d66700e745aa3b989700b4588b03e6ac9a82f34e
